import { RequestHandler } from "express";
import { PrismaClient } from "@prisma/client";
import { changePassword, loginUser, signUpUser } from "../utils/types";
import { hashData, verifyHashedData } from "../utils/hashData";
import { createToken, verifyToken } from "../utils/jwt";
import verifyEmailTemplate from "../utils/templates/verifyEmail";
import sendMail from "../utils/emailSender";
import { cloudinaryUploadImage } from "../utils/imageUploader";
import resetPasswordEmailTemplate from "../utils/templates/resetPassword";
import sendEmailUsingSMTPExpress from "../utils/sendEmail";
import sendEmailUsingNodemailer from "../utils/sendEmailNodemailer";
